name       : gnome-shell-extension-dash-to-dock
version    : '61'
release    : 7
source     :
    - https://github.com/micheleg/dash-to-dock/archive/extensions.gnome.org-v61.tar.gz : 8cea499749cca5cc0ae248a9ae5b1cda7e364526d5d1d90fd71f6aa886837c51
license    : GPL-2.0
component  : desktop.gnome
summary    : A dock for the Gnome Shell.
description: |
    A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
setup      : |
    %patch -p1 < $pkgfiles/0001-Padding-tweaks.patch
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -Dm00644 schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml $installdir/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
    %make_install
