name       : gnome-shell-extension-dash-to-dock
version    : '69'
release    : 15
source     :
    - https://github.com/micheleg/dash-to-dock/archive/extensions.gnome.org-v69.tar.gz : 113536092f0c40bf17e07d7340bc1edba62cd9e3d196d42e85144e66e5a5cda8
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A dock for the Gnome Shell.
description: |
    A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
setup      : |
    %patch -p1 < $pkgfiles/0001-Padding-tweaks.patch
    %patch -p1 < $pkgfiles/0002-Disable-trash-and-mounts-by-default.patch
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -Dm00644 schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml $installdir/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
    %make_install
