name       : gnome-shell-extension-dash-to-dock
version    : '71'
release    : 16
source     :
    - git|https://github.com/micheleg/dash-to-dock.git : a23f0c5efa82d8dca767dd323436c5998373f139
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A dock for the Gnome Shell.
description: |
    A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
builddeps  :
    - sassc
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -Dm00644 schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml $installdir/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
    %make_install
